### ISSUE TITLE
Диаграмма активностей для изменения API

### ISSUE THREAD

**Issue by AJIOB** [Kimentii/trackPlatform#1]
Исходя из вашей диаграммы активностей пользователь сам будет "выводить об ошибке". 
1) Что он будет выводить об ошибке?
2) Почему это будет делать пользователь?

**Comment by AJIOB** [comment]
Данная ошибка наблюдается во всех диаграммах активностей

**Comment by Kimentii** [comment]
Я хотел показать, что это происходит на уровне пользователя, а не то, что этим занимается пользователь.

**Comment by AJIOB** [comment]
Это не очевидно. Требуется описать это как-либо по другому
